version: '3'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile    
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
    networks:
        - networks        
volumes:
  app:  
  
networks:
  networks:
    driver: bridge  