version: '3'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile    
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
    networks:
        - networks        
  postgres:    
    image: postgres:12.12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5439:5432"
    networks:
      - postgres
    restart: unless-stopped

volumes:
  app:  
  postgres:
  
networks:
  networks:
    driver: bridge  