version: '3'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile    
    ports: 
      - "3000:3000"
    depends_on:      
      - postgres      
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development      
      DB_HOST: postgres

  postgres:    
    image: postgres:12.12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"    
    restart: unless-stopped

volumes:
  app:  
  postgres:
  
networks:
  default:
    name: franze-local
    external: true